/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [MiscItem]
    /// </summary>
    public partial interface IHarvestTarget :
        IFallout4MajorRecordInternal,
        IHarvestTargetGetter
    {
    }

    /// <summary>
    /// Implemented by: [MiscItem]
    /// </summary>
    public partial interface IHarvestTargetGetter : IFallout4MajorRecordGetter
    {
    }
}
