/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [Armor, Book]
    /// </summary>
    public partial interface IItem :
        IFallout4MajorRecordInternal,
        IItemGetter
    {
    }

    /// <summary>
    /// Implemented by: [Armor, Book]
    /// </summary>
    public partial interface IItemGetter : IFallout4MajorRecordGetter
    {
    }
}
