/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using Mutagen.Bethesda;

namespace Mutagen.Bethesda.Fallout4
{
    /// <summary>
    /// Implemented by: [Activator, Armor, Book, Container, Door, Faction, Furniture, Ingestible, Key, Light, MiscItem, MoveableStatic, Spell, TextureSet]
    /// </summary>
    public partial interface IObjectId :
        IFallout4MajorRecordInternal,
        IObjectIdGetter
    {
    }

    /// <summary>
    /// Implemented by: [Activator, Armor, Book, Container, Door, Faction, Furniture, Ingestible, Key, Light, MiscItem, MoveableStatic, Spell, TextureSet]
    /// </summary>
    public partial interface IObjectIdGetter : IFallout4MajorRecordGetter
    {
    }
}
