/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
#region Usings
using Loqui;
using Loqui.Internal;
using Mutagen.Bethesda.Binary;
using Mutagen.Bethesda.Fallout4.Internals;
using Mutagen.Bethesda.Internals;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Binary.Overlay;
using Mutagen.Bethesda.Plugins.Binary.Streams;
using Mutagen.Bethesda.Plugins.Binary.Translations;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Exceptions;
using Mutagen.Bethesda.Plugins.Internals;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Plugins.Records.Internals;
using Mutagen.Bethesda.Translations.Binary;
using Noggog;
using System;
using System.Buffers.Binary;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Text;
#endregion

#nullable enable
namespace Mutagen.Bethesda.Fallout4
{
    #region Class
    public partial class PreviewTransform :
        IEquatable<IPreviewTransformGetter>,
        ILoquiObjectSetter<PreviewTransform>,
        IPreviewTransform
    {
        #region Ctor
        public PreviewTransform()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Transform
        private readonly IFormLinkNullable<ITransformGetter> _Transform = new FormLinkNullable<ITransformGetter>();
        public IFormLinkNullable<ITransformGetter> Transform
        {
            get => _Transform;
            set => _Transform.SetTo(value);
        }
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IFormLinkNullableGetter<ITransformGetter> IPreviewTransformGetter.Transform => this.Transform;
        #endregion

        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            PreviewTransformMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IPreviewTransformGetter rhs) return false;
            return ((PreviewTransformCommon)((IPreviewTransformGetter)this).CommonInstance()!).Equals(this, rhs, crystal: null);
        }

        public bool Equals(IPreviewTransformGetter? obj)
        {
            return ((PreviewTransformCommon)((IPreviewTransformGetter)this).CommonInstance()!).Equals(this, obj, crystal: null);
        }

        public override int GetHashCode() => ((PreviewTransformCommon)((IPreviewTransformGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

        #region Mask
        public class Mask<TItem> :
            IEquatable<Mask<TItem>>,
            IMask<TItem>
        {
            #region Ctors
            public Mask(TItem Transform)
            {
                this.Transform = Transform;
            }

            #pragma warning disable CS8618
            protected Mask()
            {
            }
            #pragma warning restore CS8618

            #endregion

            #region Members
            public TItem Transform;
            #endregion

            #region Equals
            public override bool Equals(object? obj)
            {
                if (!(obj is Mask<TItem> rhs)) return false;
                return Equals(rhs);
            }

            public bool Equals(Mask<TItem>? rhs)
            {
                if (rhs == null) return false;
                if (!object.Equals(this.Transform, rhs.Transform)) return false;
                return true;
            }
            public override int GetHashCode()
            {
                var hash = new HashCode();
                hash.Add(this.Transform);
                return hash.ToHashCode();
            }

            #endregion

            #region All
            public bool All(Func<TItem, bool> eval)
            {
                if (!eval(this.Transform)) return false;
                return true;
            }
            #endregion

            #region Any
            public bool Any(Func<TItem, bool> eval)
            {
                if (eval(this.Transform)) return true;
                return false;
            }
            #endregion

            #region Translate
            public Mask<R> Translate<R>(Func<TItem, R> eval)
            {
                var ret = new PreviewTransform.Mask<R>();
                this.Translate_InternalFill(ret, eval);
                return ret;
            }

            protected void Translate_InternalFill<R>(Mask<R> obj, Func<TItem, R> eval)
            {
                obj.Transform = eval(this.Transform);
            }
            #endregion

            #region To String
            public override string ToString()
            {
                return ToString(printMask: null);
            }

            public string ToString(PreviewTransform.Mask<bool>? printMask = null)
            {
                var fg = new FileGeneration();
                ToString(fg, printMask);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, PreviewTransform.Mask<bool>? printMask = null)
            {
                fg.AppendLine($"{nameof(PreviewTransform.Mask<TItem>)} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (printMask?.Transform ?? true)
                    {
                        fg.AppendItem(Transform, "Transform");
                    }
                }
                fg.AppendLine("]");
            }
            #endregion

        }

        public class ErrorMask :
            IErrorMask,
            IErrorMask<ErrorMask>
        {
            #region Members
            public Exception? Overall { get; set; }
            private List<string>? _warnings;
            public List<string> Warnings
            {
                get
                {
                    if (_warnings == null)
                    {
                        _warnings = new List<string>();
                    }
                    return _warnings;
                }
            }
            public Exception? Transform;
            #endregion

            #region IErrorMask
            public object? GetNthMask(int index)
            {
                PreviewTransform_FieldIndex enu = (PreviewTransform_FieldIndex)index;
                switch (enu)
                {
                    case PreviewTransform_FieldIndex.Transform:
                        return Transform;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthException(int index, Exception ex)
            {
                PreviewTransform_FieldIndex enu = (PreviewTransform_FieldIndex)index;
                switch (enu)
                {
                    case PreviewTransform_FieldIndex.Transform:
                        this.Transform = ex;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthMask(int index, object obj)
            {
                PreviewTransform_FieldIndex enu = (PreviewTransform_FieldIndex)index;
                switch (enu)
                {
                    case PreviewTransform_FieldIndex.Transform:
                        this.Transform = (Exception?)obj;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public bool IsInError()
            {
                if (Overall != null) return true;
                if (Transform != null) return true;
                return false;
            }
            #endregion

            #region To String
            public override string ToString()
            {
                var fg = new FileGeneration();
                ToString(fg, null);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, string? name = null)
            {
                fg.AppendLine($"{(name ?? "ErrorMask")} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (this.Overall != null)
                    {
                        fg.AppendLine("Overall =>");
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            fg.AppendLine($"{this.Overall}");
                        }
                        fg.AppendLine("]");
                    }
                    ToString_FillInternal(fg);
                }
                fg.AppendLine("]");
            }
            protected void ToString_FillInternal(FileGeneration fg)
            {
                fg.AppendItem(Transform, "Transform");
            }
            #endregion

            #region Combine
            public ErrorMask Combine(ErrorMask? rhs)
            {
                if (rhs == null) return this;
                var ret = new ErrorMask();
                ret.Transform = this.Transform.Combine(rhs.Transform);
                return ret;
            }
            public static ErrorMask? Combine(ErrorMask? lhs, ErrorMask? rhs)
            {
                if (lhs != null && rhs != null) return lhs.Combine(rhs);
                return lhs ?? rhs;
            }
            #endregion

            #region Factory
            public static ErrorMask Factory(ErrorMaskBuilder errorMask)
            {
                return new ErrorMask();
            }
            #endregion

        }
        public class TranslationMask : ITranslationMask
        {
            #region Members
            private TranslationCrystal? _crystal;
            public readonly bool DefaultOn;
            public bool OnOverall;
            public bool Transform;
            #endregion

            #region Ctors
            public TranslationMask(
                bool defaultOn,
                bool onOverall = true)
            {
                this.DefaultOn = defaultOn;
                this.OnOverall = onOverall;
                this.Transform = defaultOn;
            }

            #endregion

            public TranslationCrystal GetCrystal()
            {
                if (_crystal != null) return _crystal;
                var ret = new List<(bool On, TranslationCrystal? SubCrystal)>();
                GetCrystal(ret);
                _crystal = new TranslationCrystal(ret.ToArray());
                return _crystal;
            }

            protected void GetCrystal(List<(bool On, TranslationCrystal? SubCrystal)> ret)
            {
                ret.Add((Transform, null));
            }

            public static implicit operator TranslationMask(bool defaultOn)
            {
                return new TranslationMask(defaultOn: defaultOn, onOverall: defaultOn);
            }

        }
        #endregion

        #region Mutagen
        public static readonly RecordType GrupRecordType = PreviewTransform_Registration.TriggeringRecordType;
        public IEnumerable<IFormLinkGetter> ContainedFormLinks => PreviewTransformCommon.Instance.GetContainedFormLinks(this);
        public void RemapLinks(IReadOnlyDictionary<FormKey, FormKey> mapping) => PreviewTransformSetterCommon.Instance.RemapLinks(this, mapping);
        #endregion

        #region Binary Translation
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => PreviewTransformBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((PreviewTransformBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }
        #region Binary Create
        public static PreviewTransform CreateFromBinary(
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            var ret = new PreviewTransform();
            ((PreviewTransformSetterCommon)((IPreviewTransformGetter)ret).CommonSetterInstance()!).CopyInFromBinary(
                item: ret,
                frame: frame,
                translationParams: translationParams);
            return ret;
        }

        #endregion

        public static bool TryCreateFromBinary(
            MutagenFrame frame,
            out PreviewTransform item,
            TypedParseParams? translationParams = null)
        {
            var startPos = frame.Position;
            item = CreateFromBinary(
                frame: frame,
                translationParams: translationParams);
            return startPos != frame.Position;
        }
        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);

        void IClearable.Clear()
        {
            ((PreviewTransformSetterCommon)((IPreviewTransformGetter)this).CommonSetterInstance()!).Clear(this);
        }

        internal static PreviewTransform GetNew()
        {
            return new PreviewTransform();
        }

    }
    #endregion

    #region Interface
    public partial interface IPreviewTransform :
        IFormLinkContainer,
        ILoquiObjectSetter<IPreviewTransform>,
        IPreviewTransformGetter
    {
        new IFormLinkNullable<ITransformGetter> Transform { get; set; }
    }

    public partial interface IPreviewTransformGetter :
        ILoquiObject,
        IBinaryItem,
        IFormLinkContainerGetter,
        ILoquiObject<IPreviewTransformGetter>
    {
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object? CommonSetterInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonSetterTranslationInstance();
        static ILoquiRegistration StaticRegistration => PreviewTransform_Registration.Instance;
        IFormLinkNullableGetter<ITransformGetter> Transform { get; }

    }

    #endregion

    #region Common MixIn
    public static partial class PreviewTransformMixIn
    {
        public static void Clear(this IPreviewTransform item)
        {
            ((PreviewTransformSetterCommon)((IPreviewTransformGetter)item).CommonSetterInstance()!).Clear(item: item);
        }

        public static PreviewTransform.Mask<bool> GetEqualsMask(
            this IPreviewTransformGetter item,
            IPreviewTransformGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            return ((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).GetEqualsMask(
                item: item,
                rhs: rhs,
                include: include);
        }

        public static string ToString(
            this IPreviewTransformGetter item,
            string? name = null,
            PreviewTransform.Mask<bool>? printMask = null)
        {
            return ((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).ToString(
                item: item,
                name: name,
                printMask: printMask);
        }

        public static void ToString(
            this IPreviewTransformGetter item,
            FileGeneration fg,
            string? name = null,
            PreviewTransform.Mask<bool>? printMask = null)
        {
            ((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
        }

        public static bool Equals(
            this IPreviewTransformGetter item,
            IPreviewTransformGetter rhs,
            PreviewTransform.TranslationMask? equalsMask = null)
        {
            return ((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).Equals(
                lhs: item,
                rhs: rhs,
                crystal: equalsMask?.GetCrystal());
        }

        public static void DeepCopyIn(
            this IPreviewTransform lhs,
            IPreviewTransformGetter rhs)
        {
            ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: default,
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IPreviewTransform lhs,
            IPreviewTransformGetter rhs,
            PreviewTransform.TranslationMask? copyMask = null)
        {
            ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IPreviewTransform lhs,
            IPreviewTransformGetter rhs,
            out PreviewTransform.ErrorMask errorMask,
            PreviewTransform.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
            errorMask = PreviewTransform.ErrorMask.Factory(errorMaskBuilder);
        }

        public static void DeepCopyIn(
            this IPreviewTransform lhs,
            IPreviewTransformGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask)
        {
            ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: false);
        }

        public static PreviewTransform DeepCopy(
            this IPreviewTransformGetter item,
            PreviewTransform.TranslationMask? copyMask = null)
        {
            return ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask);
        }

        public static PreviewTransform DeepCopy(
            this IPreviewTransformGetter item,
            out PreviewTransform.ErrorMask errorMask,
            PreviewTransform.TranslationMask? copyMask = null)
        {
            return ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: out errorMask);
        }

        public static PreviewTransform DeepCopy(
            this IPreviewTransformGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            return ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: errorMask);
        }

        #region Binary Translation
        public static void CopyInFromBinary(
            this IPreviewTransform item,
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            ((PreviewTransformSetterCommon)((IPreviewTransformGetter)item).CommonSetterInstance()!).CopyInFromBinary(
                item: item,
                frame: frame,
                translationParams: translationParams);
        }

        #endregion

    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4.Internals
{
    #region Field Index
    public enum PreviewTransform_FieldIndex
    {
        Transform = 0,
    }
    #endregion

    #region Registration
    public partial class PreviewTransform_Registration : ILoquiRegistration
    {
        public static readonly PreviewTransform_Registration Instance = new PreviewTransform_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_Fallout4.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_Fallout4.ProtocolKey,
            msgID: 142,
            version: 0);

        public const string GUID = "7f759050-a8c1-4dd5-9306-a9b8b9ccd547";

        public const ushort AdditionalFieldCount = 1;

        public const ushort FieldCount = 1;

        public static readonly Type MaskType = typeof(PreviewTransform.Mask<>);

        public static readonly Type ErrorMaskType = typeof(PreviewTransform.ErrorMask);

        public static readonly Type ClassType = typeof(PreviewTransform);

        public static readonly Type GetterType = typeof(IPreviewTransformGetter);

        public static readonly Type? InternalGetterType = null;

        public static readonly Type SetterType = typeof(IPreviewTransform);

        public static readonly Type? InternalSetterType = null;

        public const string FullName = "Mutagen.Bethesda.Fallout4.PreviewTransform";

        public const string Name = "PreviewTransform";

        public const string Namespace = "Mutagen.Bethesda.Fallout4";

        public const byte GenericCount = 0;

        public static readonly Type? GenericRegistrationType = null;

        public static readonly RecordType TriggeringRecordType = RecordTypes.PTRN;
        public static readonly Type BinaryWriteTranslation = typeof(PreviewTransformBinaryWriteTranslation);
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type? ILoquiRegistration.InternalSetterType => InternalSetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type? ILoquiRegistration.InternalGetterType => InternalGetterType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type? ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => throw new NotImplementedException();
        string ILoquiRegistration.GetNthName(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsNthDerivative(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsProtected(ushort index) => throw new NotImplementedException();
        Type ILoquiRegistration.GetNthType(ushort index) => throw new NotImplementedException();
        #endregion

    }
    #endregion

    #region Common
    public partial class PreviewTransformSetterCommon
    {
        public static readonly PreviewTransformSetterCommon Instance = new PreviewTransformSetterCommon();

        partial void ClearPartial();
        
        public void Clear(IPreviewTransform item)
        {
            ClearPartial();
            item.Transform.Clear();
        }
        
        #region Mutagen
        public void RemapLinks(IPreviewTransform obj, IReadOnlyDictionary<FormKey, FormKey> mapping)
        {
            obj.Transform.Relink(mapping);
        }
        
        #endregion
        
        #region Binary Translation
        public virtual void CopyInFromBinary(
            IPreviewTransform item,
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            frame = frame.SpawnWithFinalPosition(HeaderTranslation.ParseSubrecord(
                frame.Reader,
                translationParams.ConvertToCustom(RecordTypes.PTRN),
                translationParams?.LengthOverride));
            PluginUtilityTranslation.SubrecordParse(
                record: item,
                frame: frame,
                translationParams: translationParams,
                fillStructs: PreviewTransformBinaryCreateTranslation.FillBinaryStructs);
        }
        
        #endregion
        
    }
    public partial class PreviewTransformCommon
    {
        public static readonly PreviewTransformCommon Instance = new PreviewTransformCommon();

        public PreviewTransform.Mask<bool> GetEqualsMask(
            IPreviewTransformGetter item,
            IPreviewTransformGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new PreviewTransform.Mask<bool>(false);
            ((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }
        
        public void FillEqualsMask(
            IPreviewTransformGetter item,
            IPreviewTransformGetter rhs,
            PreviewTransform.Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.Transform = item.Transform.Equals(rhs.Transform);
        }
        
        public string ToString(
            IPreviewTransformGetter item,
            string? name = null,
            PreviewTransform.Mask<bool>? printMask = null)
        {
            var fg = new FileGeneration();
            ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
            return fg.ToString();
        }
        
        public void ToString(
            IPreviewTransformGetter item,
            FileGeneration fg,
            string? name = null,
            PreviewTransform.Mask<bool>? printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"PreviewTransform =>");
            }
            else
            {
                fg.AppendLine($"{name} (PreviewTransform) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                ToStringFields(
                    item: item,
                    fg: fg,
                    printMask: printMask);
            }
            fg.AppendLine("]");
        }
        
        protected static void ToStringFields(
            IPreviewTransformGetter item,
            FileGeneration fg,
            PreviewTransform.Mask<bool>? printMask = null)
        {
            if (printMask?.Transform ?? true)
            {
                fg.AppendItem(item.Transform.FormKeyNullable, "Transform");
            }
        }
        
        #region Equals and Hash
        public virtual bool Equals(
            IPreviewTransformGetter? lhs,
            IPreviewTransformGetter? rhs,
            TranslationCrystal? crystal)
        {
            if (!EqualsMaskHelper.RefEquality(lhs, rhs, out var isEqual)) return isEqual;
            if ((crystal?.GetShouldTranslate((int)PreviewTransform_FieldIndex.Transform) ?? true))
            {
                if (!lhs.Transform.Equals(rhs.Transform)) return false;
            }
            return true;
        }
        
        public virtual int GetHashCode(IPreviewTransformGetter item)
        {
            var hash = new HashCode();
            hash.Add(item.Transform);
            return hash.ToHashCode();
        }
        
        #endregion
        
        
        public object GetNew()
        {
            return PreviewTransform.GetNew();
        }
        
        #region Mutagen
        public IEnumerable<IFormLinkGetter> GetContainedFormLinks(IPreviewTransformGetter obj)
        {
            if (obj.Transform.FormKeyNullable.HasValue)
            {
                yield return FormLinkInformation.Factory(obj.Transform);
            }
            yield break;
        }
        
        #endregion
        
    }
    public partial class PreviewTransformSetterTranslationCommon
    {
        public static readonly PreviewTransformSetterTranslationCommon Instance = new PreviewTransformSetterTranslationCommon();

        #region DeepCopyIn
        public void DeepCopyIn(
            IPreviewTransform item,
            IPreviewTransformGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask,
            bool deepCopy)
        {
            if ((copyMask?.GetShouldTranslate((int)PreviewTransform_FieldIndex.Transform) ?? true))
            {
                item.Transform.SetTo(rhs.Transform.FormKeyNullable);
            }
        }
        
        #endregion
        
        public PreviewTransform DeepCopy(
            IPreviewTransformGetter item,
            PreviewTransform.TranslationMask? copyMask = null)
        {
            PreviewTransform ret = (PreviewTransform)((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).GetNew();
            ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: null,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            return ret;
        }
        
        public PreviewTransform DeepCopy(
            IPreviewTransformGetter item,
            out PreviewTransform.ErrorMask errorMask,
            PreviewTransform.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            PreviewTransform ret = (PreviewTransform)((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).GetNew();
            ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                ret,
                item,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            errorMask = PreviewTransform.ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }
        
        public PreviewTransform DeepCopy(
            IPreviewTransformGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            PreviewTransform ret = (PreviewTransform)((PreviewTransformCommon)((IPreviewTransformGetter)item).CommonInstance()!).GetNew();
            ((PreviewTransformSetterTranslationCommon)((IPreviewTransformGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: true);
            return ret;
        }
        
    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4
{
    public partial class PreviewTransform
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => PreviewTransform_Registration.Instance;
        public static PreviewTransform_Registration StaticRegistration => PreviewTransform_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => PreviewTransformCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterInstance()
        {
            return PreviewTransformSetterCommon.Instance;
        }
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => PreviewTransformSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IPreviewTransformGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object IPreviewTransformGetter.CommonSetterInstance() => this.CommonSetterInstance();
        [DebuggerStepThrough]
        object IPreviewTransformGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

    }
}

#region Modules
#region Binary Translation
namespace Mutagen.Bethesda.Fallout4.Internals
{
    public partial class PreviewTransformBinaryWriteTranslation : IBinaryWriteTranslator
    {
        public readonly static PreviewTransformBinaryWriteTranslation Instance = new PreviewTransformBinaryWriteTranslation();

        public static void WriteEmbedded(
            IPreviewTransformGetter item,
            MutagenWriter writer)
        {
            FormLinkBinaryTranslation.Instance.WriteNullable(
                writer: writer,
                item: item.Transform);
        }

        public void Write(
            MutagenWriter writer,
            IPreviewTransformGetter item,
            TypedWriteParams? translationParams = null)
        {
            using (HeaderExport.Subrecord(
                writer: writer,
                record: translationParams.ConvertToCustom(RecordTypes.PTRN),
                overflowRecord: translationParams?.OverflowRecordType,
                out var writerToUse))
            {
                WriteEmbedded(
                    item: item,
                    writer: writerToUse);
            }
        }

        public void Write(
            MutagenWriter writer,
            object item,
            TypedWriteParams? translationParams = null)
        {
            Write(
                item: (IPreviewTransformGetter)item,
                writer: writer,
                translationParams: translationParams);
        }

    }

    public partial class PreviewTransformBinaryCreateTranslation
    {
        public readonly static PreviewTransformBinaryCreateTranslation Instance = new PreviewTransformBinaryCreateTranslation();

        public static void FillBinaryStructs(
            IPreviewTransform item,
            MutagenFrame frame)
        {
            if (frame.Complete) return;
            item.Transform.SetTo(FormLinkBinaryTranslation.Instance.Parse(reader: frame));
        }

    }

}
namespace Mutagen.Bethesda.Fallout4
{
    #region Binary Write Mixins
    public static class PreviewTransformBinaryTranslationMixIn
    {
        public static void WriteToBinary(
            this IPreviewTransformGetter item,
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((PreviewTransformBinaryWriteTranslation)item.BinaryWriteTranslator).Write(
                item: item,
                writer: writer,
                translationParams: translationParams);
        }

    }
    #endregion


}
namespace Mutagen.Bethesda.Fallout4.Internals
{
    public partial class PreviewTransformBinaryOverlay :
        PluginBinaryOverlay,
        IPreviewTransformGetter
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => PreviewTransform_Registration.Instance;
        public static PreviewTransform_Registration StaticRegistration => PreviewTransform_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => PreviewTransformCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => PreviewTransformSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IPreviewTransformGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object? IPreviewTransformGetter.CommonSetterInstance() => null;
        [DebuggerStepThrough]
        object IPreviewTransformGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);

        public IEnumerable<IFormLinkGetter> ContainedFormLinks => PreviewTransformCommon.Instance.GetContainedFormLinks(this);
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => PreviewTransformBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((PreviewTransformBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }

        public IFormLinkNullableGetter<ITransformGetter> Transform => new FormLinkNullable<ITransformGetter>(FormKey.Factory(_package.MetaData.MasterReferences!, BinaryPrimitives.ReadUInt32LittleEndian(_data.Span.Slice(0x0, 0x4))));
        partial void CustomFactoryEnd(
            OverlayStream stream,
            int finalPos,
            int offset);

        partial void CustomCtor();
        protected PreviewTransformBinaryOverlay(
            ReadOnlyMemorySlice<byte> bytes,
            BinaryOverlayFactoryPackage package)
            : base(
                bytes: bytes,
                package: package)
        {
            this.CustomCtor();
        }

        public static PreviewTransformBinaryOverlay PreviewTransformFactory(
            OverlayStream stream,
            BinaryOverlayFactoryPackage package,
            TypedParseParams? parseParams = null)
        {
            var ret = new PreviewTransformBinaryOverlay(
                bytes: HeaderTranslation.ExtractSubrecordMemory(stream.RemainingMemory, package.MetaData.Constants, parseParams),
                package: package);
            var finalPos = checked((int)(stream.Position + stream.GetSubrecord().TotalLength));
            int offset = stream.Position + package.MetaData.Constants.SubConstants.TypeAndLengthLength;
            stream.Position += 0x4 + package.MetaData.Constants.SubConstants.HeaderLength;
            ret.CustomFactoryEnd(
                stream: stream,
                finalPos: stream.Length,
                offset: offset);
            return ret;
        }

        public static PreviewTransformBinaryOverlay PreviewTransformFactory(
            ReadOnlyMemorySlice<byte> slice,
            BinaryOverlayFactoryPackage package,
            TypedParseParams? parseParams = null)
        {
            return PreviewTransformFactory(
                stream: new OverlayStream(slice, package),
                package: package,
                parseParams: parseParams);
        }

        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            PreviewTransformMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IPreviewTransformGetter rhs) return false;
            return ((PreviewTransformCommon)((IPreviewTransformGetter)this).CommonInstance()!).Equals(this, rhs, crystal: null);
        }

        public bool Equals(IPreviewTransformGetter? obj)
        {
            return ((PreviewTransformCommon)((IPreviewTransformGetter)this).CommonInstance()!).Equals(this, obj, crystal: null);
        }

        public override int GetHashCode() => ((PreviewTransformCommon)((IPreviewTransformGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

    }

}
#endregion

#endregion

