/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
#region Usings
using Loqui;
using Loqui.Internal;
using Mutagen.Bethesda.Binary;
using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Fallout4.Internals;
using Mutagen.Bethesda.Internals;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Binary.Overlay;
using Mutagen.Bethesda.Plugins.Binary.Streams;
using Mutagen.Bethesda.Plugins.Binary.Translations;
using Mutagen.Bethesda.Plugins.Exceptions;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Plugins.Records.Internals;
using Mutagen.Bethesda.Translations.Binary;
using Noggog;
using System;
using System.Buffers.Binary;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Text;
#endregion

#nullable enable
namespace Mutagen.Bethesda.Fallout4
{
    #region Class
    public partial class ScriptStructMember :
        IEquatable<IScriptStructMemberGetter>,
        ILoquiObjectSetter<ScriptStructMember>,
        IScriptStructMember
    {
        #region Ctor
        public ScriptStructMember()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region MemberName
        public String MemberName { get; set; } = string.Empty;
        #endregion
        #region MemberFlags
        public ScriptEntry.Flag MemberFlags { get; set; } = default;
        #endregion
        #region MemberProperties
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private ExtendedList<ScriptPropertyStructMember> _MemberProperties = new ExtendedList<ScriptPropertyStructMember>();
        public ExtendedList<ScriptPropertyStructMember> MemberProperties
        {
            get => this._MemberProperties;
            init => this._MemberProperties = value;
        }
        #region Interface Members
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        IReadOnlyList<IScriptPropertyStructMemberGetter> IScriptStructMemberGetter.MemberProperties => _MemberProperties;
        #endregion

        #endregion

        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            ScriptStructMemberMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IScriptStructMemberGetter rhs) return false;
            return ((ScriptStructMemberCommon)((IScriptStructMemberGetter)this).CommonInstance()!).Equals(this, rhs, crystal: null);
        }

        public bool Equals(IScriptStructMemberGetter? obj)
        {
            return ((ScriptStructMemberCommon)((IScriptStructMemberGetter)this).CommonInstance()!).Equals(this, obj, crystal: null);
        }

        public override int GetHashCode() => ((ScriptStructMemberCommon)((IScriptStructMemberGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

        #region Mask
        public class Mask<TItem> :
            IEquatable<Mask<TItem>>,
            IMask<TItem>
        {
            #region Ctors
            public Mask(TItem initialValue)
            {
                this.MemberName = initialValue;
                this.MemberFlags = initialValue;
                this.MemberProperties = new MaskItem<TItem, IEnumerable<MaskItemIndexed<TItem, ScriptPropertyStructMember.Mask<TItem>?>>?>(initialValue, Enumerable.Empty<MaskItemIndexed<TItem, ScriptPropertyStructMember.Mask<TItem>?>>());
            }

            public Mask(
                TItem MemberName,
                TItem MemberFlags,
                TItem MemberProperties)
            {
                this.MemberName = MemberName;
                this.MemberFlags = MemberFlags;
                this.MemberProperties = new MaskItem<TItem, IEnumerable<MaskItemIndexed<TItem, ScriptPropertyStructMember.Mask<TItem>?>>?>(MemberProperties, Enumerable.Empty<MaskItemIndexed<TItem, ScriptPropertyStructMember.Mask<TItem>?>>());
            }

            #pragma warning disable CS8618
            protected Mask()
            {
            }
            #pragma warning restore CS8618

            #endregion

            #region Members
            public TItem MemberName;
            public TItem MemberFlags;
            public MaskItem<TItem, IEnumerable<MaskItemIndexed<TItem, ScriptPropertyStructMember.Mask<TItem>?>>?>? MemberProperties;
            #endregion

            #region Equals
            public override bool Equals(object? obj)
            {
                if (!(obj is Mask<TItem> rhs)) return false;
                return Equals(rhs);
            }

            public bool Equals(Mask<TItem>? rhs)
            {
                if (rhs == null) return false;
                if (!object.Equals(this.MemberName, rhs.MemberName)) return false;
                if (!object.Equals(this.MemberFlags, rhs.MemberFlags)) return false;
                if (!object.Equals(this.MemberProperties, rhs.MemberProperties)) return false;
                return true;
            }
            public override int GetHashCode()
            {
                var hash = new HashCode();
                hash.Add(this.MemberName);
                hash.Add(this.MemberFlags);
                hash.Add(this.MemberProperties);
                return hash.ToHashCode();
            }

            #endregion

            #region All
            public bool All(Func<TItem, bool> eval)
            {
                if (!eval(this.MemberName)) return false;
                if (!eval(this.MemberFlags)) return false;
                if (this.MemberProperties != null)
                {
                    if (!eval(this.MemberProperties.Overall)) return false;
                    if (this.MemberProperties.Specific != null)
                    {
                        foreach (var item in this.MemberProperties.Specific)
                        {
                            if (!eval(item.Overall)) return false;
                            if (item.Specific != null && !item.Specific.All(eval)) return false;
                        }
                    }
                }
                return true;
            }
            #endregion

            #region Any
            public bool Any(Func<TItem, bool> eval)
            {
                if (eval(this.MemberName)) return true;
                if (eval(this.MemberFlags)) return true;
                if (this.MemberProperties != null)
                {
                    if (eval(this.MemberProperties.Overall)) return true;
                    if (this.MemberProperties.Specific != null)
                    {
                        foreach (var item in this.MemberProperties.Specific)
                        {
                            if (!eval(item.Overall)) return false;
                            if (item.Specific != null && !item.Specific.All(eval)) return false;
                        }
                    }
                }
                return false;
            }
            #endregion

            #region Translate
            public Mask<R> Translate<R>(Func<TItem, R> eval)
            {
                var ret = new ScriptStructMember.Mask<R>();
                this.Translate_InternalFill(ret, eval);
                return ret;
            }

            protected void Translate_InternalFill<R>(Mask<R> obj, Func<TItem, R> eval)
            {
                obj.MemberName = eval(this.MemberName);
                obj.MemberFlags = eval(this.MemberFlags);
                if (MemberProperties != null)
                {
                    obj.MemberProperties = new MaskItem<R, IEnumerable<MaskItemIndexed<R, ScriptPropertyStructMember.Mask<R>?>>?>(eval(this.MemberProperties.Overall), Enumerable.Empty<MaskItemIndexed<R, ScriptPropertyStructMember.Mask<R>?>>());
                    if (MemberProperties.Specific != null)
                    {
                        var l = new List<MaskItemIndexed<R, ScriptPropertyStructMember.Mask<R>?>>();
                        obj.MemberProperties.Specific = l;
                        foreach (var item in MemberProperties.Specific.WithIndex())
                        {
                            MaskItemIndexed<R, ScriptPropertyStructMember.Mask<R>?>? mask = item.Item == null ? null : new MaskItemIndexed<R, ScriptPropertyStructMember.Mask<R>?>(item.Item.Index, eval(item.Item.Overall), item.Item.Specific?.Translate(eval));
                            if (mask == null) continue;
                            l.Add(mask);
                        }
                    }
                }
            }
            #endregion

            #region To String
            public override string ToString()
            {
                return ToString(printMask: null);
            }

            public string ToString(ScriptStructMember.Mask<bool>? printMask = null)
            {
                var fg = new FileGeneration();
                ToString(fg, printMask);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, ScriptStructMember.Mask<bool>? printMask = null)
            {
                fg.AppendLine($"{nameof(ScriptStructMember.Mask<TItem>)} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (printMask?.MemberName ?? true)
                    {
                        fg.AppendItem(MemberName, "MemberName");
                    }
                    if (printMask?.MemberFlags ?? true)
                    {
                        fg.AppendItem(MemberFlags, "MemberFlags");
                    }
                    if ((printMask?.MemberProperties?.Overall ?? true)
                        && MemberProperties is {} MemberPropertiesItem)
                    {
                        fg.AppendLine("MemberProperties =>");
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            fg.AppendItem(MemberPropertiesItem.Overall);
                            if (MemberPropertiesItem.Specific != null)
                            {
                                foreach (var subItem in MemberPropertiesItem.Specific)
                                {
                                    fg.AppendLine("[");
                                    using (new DepthWrapper(fg))
                                    {
                                        subItem?.ToString(fg);
                                    }
                                    fg.AppendLine("]");
                                }
                            }
                        }
                        fg.AppendLine("]");
                    }
                }
                fg.AppendLine("]");
            }
            #endregion

        }

        public class ErrorMask :
            IErrorMask,
            IErrorMask<ErrorMask>
        {
            #region Members
            public Exception? Overall { get; set; }
            private List<string>? _warnings;
            public List<string> Warnings
            {
                get
                {
                    if (_warnings == null)
                    {
                        _warnings = new List<string>();
                    }
                    return _warnings;
                }
            }
            public Exception? MemberName;
            public Exception? MemberFlags;
            public MaskItem<Exception?, IEnumerable<MaskItem<Exception?, ScriptPropertyStructMember.ErrorMask?>>?>? MemberProperties;
            #endregion

            #region IErrorMask
            public object? GetNthMask(int index)
            {
                ScriptStructMember_FieldIndex enu = (ScriptStructMember_FieldIndex)index;
                switch (enu)
                {
                    case ScriptStructMember_FieldIndex.MemberName:
                        return MemberName;
                    case ScriptStructMember_FieldIndex.MemberFlags:
                        return MemberFlags;
                    case ScriptStructMember_FieldIndex.MemberProperties:
                        return MemberProperties;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthException(int index, Exception ex)
            {
                ScriptStructMember_FieldIndex enu = (ScriptStructMember_FieldIndex)index;
                switch (enu)
                {
                    case ScriptStructMember_FieldIndex.MemberName:
                        this.MemberName = ex;
                        break;
                    case ScriptStructMember_FieldIndex.MemberFlags:
                        this.MemberFlags = ex;
                        break;
                    case ScriptStructMember_FieldIndex.MemberProperties:
                        this.MemberProperties = new MaskItem<Exception?, IEnumerable<MaskItem<Exception?, ScriptPropertyStructMember.ErrorMask?>>?>(ex, null);
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthMask(int index, object obj)
            {
                ScriptStructMember_FieldIndex enu = (ScriptStructMember_FieldIndex)index;
                switch (enu)
                {
                    case ScriptStructMember_FieldIndex.MemberName:
                        this.MemberName = (Exception?)obj;
                        break;
                    case ScriptStructMember_FieldIndex.MemberFlags:
                        this.MemberFlags = (Exception?)obj;
                        break;
                    case ScriptStructMember_FieldIndex.MemberProperties:
                        this.MemberProperties = (MaskItem<Exception?, IEnumerable<MaskItem<Exception?, ScriptPropertyStructMember.ErrorMask?>>?>)obj;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public bool IsInError()
            {
                if (Overall != null) return true;
                if (MemberName != null) return true;
                if (MemberFlags != null) return true;
                if (MemberProperties != null) return true;
                return false;
            }
            #endregion

            #region To String
            public override string ToString()
            {
                var fg = new FileGeneration();
                ToString(fg, null);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, string? name = null)
            {
                fg.AppendLine($"{(name ?? "ErrorMask")} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (this.Overall != null)
                    {
                        fg.AppendLine("Overall =>");
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            fg.AppendLine($"{this.Overall}");
                        }
                        fg.AppendLine("]");
                    }
                    ToString_FillInternal(fg);
                }
                fg.AppendLine("]");
            }
            protected void ToString_FillInternal(FileGeneration fg)
            {
                fg.AppendItem(MemberName, "MemberName");
                fg.AppendItem(MemberFlags, "MemberFlags");
                if (MemberProperties is {} MemberPropertiesItem)
                {
                    fg.AppendLine("MemberProperties =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendItem(MemberPropertiesItem.Overall);
                        if (MemberPropertiesItem.Specific != null)
                        {
                            foreach (var subItem in MemberPropertiesItem.Specific)
                            {
                                fg.AppendLine("[");
                                using (new DepthWrapper(fg))
                                {
                                    subItem?.ToString(fg);
                                }
                                fg.AppendLine("]");
                            }
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            #endregion

            #region Combine
            public ErrorMask Combine(ErrorMask? rhs)
            {
                if (rhs == null) return this;
                var ret = new ErrorMask();
                ret.MemberName = this.MemberName.Combine(rhs.MemberName);
                ret.MemberFlags = this.MemberFlags.Combine(rhs.MemberFlags);
                ret.MemberProperties = new MaskItem<Exception?, IEnumerable<MaskItem<Exception?, ScriptPropertyStructMember.ErrorMask?>>?>(ExceptionExt.Combine(this.MemberProperties?.Overall, rhs.MemberProperties?.Overall), ExceptionExt.Combine(this.MemberProperties?.Specific, rhs.MemberProperties?.Specific));
                return ret;
            }
            public static ErrorMask? Combine(ErrorMask? lhs, ErrorMask? rhs)
            {
                if (lhs != null && rhs != null) return lhs.Combine(rhs);
                return lhs ?? rhs;
            }
            #endregion

            #region Factory
            public static ErrorMask Factory(ErrorMaskBuilder errorMask)
            {
                return new ErrorMask();
            }
            #endregion

        }
        public class TranslationMask : ITranslationMask
        {
            #region Members
            private TranslationCrystal? _crystal;
            public readonly bool DefaultOn;
            public bool OnOverall;
            public bool MemberName;
            public bool MemberFlags;
            public ScriptPropertyStructMember.TranslationMask? MemberProperties;
            #endregion

            #region Ctors
            public TranslationMask(
                bool defaultOn,
                bool onOverall = true)
            {
                this.DefaultOn = defaultOn;
                this.OnOverall = onOverall;
                this.MemberName = defaultOn;
                this.MemberFlags = defaultOn;
            }

            #endregion

            public TranslationCrystal GetCrystal()
            {
                if (_crystal != null) return _crystal;
                var ret = new List<(bool On, TranslationCrystal? SubCrystal)>();
                GetCrystal(ret);
                _crystal = new TranslationCrystal(ret.ToArray());
                return _crystal;
            }

            protected void GetCrystal(List<(bool On, TranslationCrystal? SubCrystal)> ret)
            {
                ret.Add((MemberName, null));
                ret.Add((MemberFlags, null));
                ret.Add((MemberProperties == null ? DefaultOn : !MemberProperties.GetCrystal().CopyNothing, MemberProperties?.GetCrystal()));
            }

            public static implicit operator TranslationMask(bool defaultOn)
            {
                return new TranslationMask(defaultOn: defaultOn, onOverall: defaultOn);
            }

        }
        #endregion

        #region Binary Translation
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => ScriptStructMemberBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((ScriptStructMemberBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }
        #region Binary Create
        public static ScriptStructMember CreateFromBinary(
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            var ret = new ScriptStructMember();
            ((ScriptStructMemberSetterCommon)((IScriptStructMemberGetter)ret).CommonSetterInstance()!).CopyInFromBinary(
                item: ret,
                frame: frame,
                translationParams: translationParams);
            return ret;
        }

        #endregion

        public static bool TryCreateFromBinary(
            MutagenFrame frame,
            out ScriptStructMember item,
            TypedParseParams? translationParams = null)
        {
            var startPos = frame.Position;
            item = CreateFromBinary(
                frame: frame,
                translationParams: translationParams);
            return startPos != frame.Position;
        }
        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);

        void IClearable.Clear()
        {
            ((ScriptStructMemberSetterCommon)((IScriptStructMemberGetter)this).CommonSetterInstance()!).Clear(this);
        }

        internal static ScriptStructMember GetNew()
        {
            return new ScriptStructMember();
        }

    }
    #endregion

    #region Interface
    public partial interface IScriptStructMember :
        ILoquiObjectSetter<IScriptStructMember>,
        IScriptStructMemberGetter
    {
        new String MemberName { get; set; }
        new ScriptEntry.Flag MemberFlags { get; set; }
        new ExtendedList<ScriptPropertyStructMember> MemberProperties { get; }
    }

    public partial interface IScriptStructMemberGetter :
        ILoquiObject,
        IBinaryItem,
        ILoquiObject<IScriptStructMemberGetter>
    {
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object? CommonSetterInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonSetterTranslationInstance();
        static ILoquiRegistration StaticRegistration => ScriptStructMember_Registration.Instance;
        String MemberName { get; }
        ScriptEntry.Flag MemberFlags { get; }
        IReadOnlyList<IScriptPropertyStructMemberGetter> MemberProperties { get; }

    }

    #endregion

    #region Common MixIn
    public static partial class ScriptStructMemberMixIn
    {
        public static void Clear(this IScriptStructMember item)
        {
            ((ScriptStructMemberSetterCommon)((IScriptStructMemberGetter)item).CommonSetterInstance()!).Clear(item: item);
        }

        public static ScriptStructMember.Mask<bool> GetEqualsMask(
            this IScriptStructMemberGetter item,
            IScriptStructMemberGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            return ((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).GetEqualsMask(
                item: item,
                rhs: rhs,
                include: include);
        }

        public static string ToString(
            this IScriptStructMemberGetter item,
            string? name = null,
            ScriptStructMember.Mask<bool>? printMask = null)
        {
            return ((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).ToString(
                item: item,
                name: name,
                printMask: printMask);
        }

        public static void ToString(
            this IScriptStructMemberGetter item,
            FileGeneration fg,
            string? name = null,
            ScriptStructMember.Mask<bool>? printMask = null)
        {
            ((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
        }

        public static bool Equals(
            this IScriptStructMemberGetter item,
            IScriptStructMemberGetter rhs,
            ScriptStructMember.TranslationMask? equalsMask = null)
        {
            return ((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).Equals(
                lhs: item,
                rhs: rhs,
                crystal: equalsMask?.GetCrystal());
        }

        public static void DeepCopyIn(
            this IScriptStructMember lhs,
            IScriptStructMemberGetter rhs)
        {
            ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: default,
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IScriptStructMember lhs,
            IScriptStructMemberGetter rhs,
            ScriptStructMember.TranslationMask? copyMask = null)
        {
            ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IScriptStructMember lhs,
            IScriptStructMemberGetter rhs,
            out ScriptStructMember.ErrorMask errorMask,
            ScriptStructMember.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
            errorMask = ScriptStructMember.ErrorMask.Factory(errorMaskBuilder);
        }

        public static void DeepCopyIn(
            this IScriptStructMember lhs,
            IScriptStructMemberGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask)
        {
            ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: false);
        }

        public static ScriptStructMember DeepCopy(
            this IScriptStructMemberGetter item,
            ScriptStructMember.TranslationMask? copyMask = null)
        {
            return ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask);
        }

        public static ScriptStructMember DeepCopy(
            this IScriptStructMemberGetter item,
            out ScriptStructMember.ErrorMask errorMask,
            ScriptStructMember.TranslationMask? copyMask = null)
        {
            return ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: out errorMask);
        }

        public static ScriptStructMember DeepCopy(
            this IScriptStructMemberGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            return ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: errorMask);
        }

        #region Binary Translation
        public static void CopyInFromBinary(
            this IScriptStructMember item,
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            ((ScriptStructMemberSetterCommon)((IScriptStructMemberGetter)item).CommonSetterInstance()!).CopyInFromBinary(
                item: item,
                frame: frame,
                translationParams: translationParams);
        }

        #endregion

    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4.Internals
{
    #region Field Index
    public enum ScriptStructMember_FieldIndex
    {
        MemberName = 0,
        MemberFlags = 1,
        MemberProperties = 2,
    }
    #endregion

    #region Registration
    public partial class ScriptStructMember_Registration : ILoquiRegistration
    {
        public static readonly ScriptStructMember_Registration Instance = new ScriptStructMember_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_Fallout4.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_Fallout4.ProtocolKey,
            msgID: 214,
            version: 0);

        public const string GUID = "755abef0-bf3e-4626-abbc-192a92ee594c";

        public const ushort AdditionalFieldCount = 3;

        public const ushort FieldCount = 3;

        public static readonly Type MaskType = typeof(ScriptStructMember.Mask<>);

        public static readonly Type ErrorMaskType = typeof(ScriptStructMember.ErrorMask);

        public static readonly Type ClassType = typeof(ScriptStructMember);

        public static readonly Type GetterType = typeof(IScriptStructMemberGetter);

        public static readonly Type? InternalGetterType = null;

        public static readonly Type SetterType = typeof(IScriptStructMember);

        public static readonly Type? InternalSetterType = null;

        public const string FullName = "Mutagen.Bethesda.Fallout4.ScriptStructMember";

        public const string Name = "ScriptStructMember";

        public const string Namespace = "Mutagen.Bethesda.Fallout4";

        public const byte GenericCount = 0;

        public static readonly Type? GenericRegistrationType = null;

        public static readonly Type BinaryWriteTranslation = typeof(ScriptStructMemberBinaryWriteTranslation);
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type? ILoquiRegistration.InternalSetterType => InternalSetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type? ILoquiRegistration.InternalGetterType => InternalGetterType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type? ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => throw new NotImplementedException();
        string ILoquiRegistration.GetNthName(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsNthDerivative(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsProtected(ushort index) => throw new NotImplementedException();
        Type ILoquiRegistration.GetNthType(ushort index) => throw new NotImplementedException();
        #endregion

    }
    #endregion

    #region Common
    public partial class ScriptStructMemberSetterCommon
    {
        public static readonly ScriptStructMemberSetterCommon Instance = new ScriptStructMemberSetterCommon();

        partial void ClearPartial();
        
        public void Clear(IScriptStructMember item)
        {
            ClearPartial();
            item.MemberName = string.Empty;
            item.MemberFlags = default;
            item.MemberProperties.Clear();
        }
        
        #region Mutagen
        public void RemapLinks(IScriptStructMember obj, IReadOnlyDictionary<FormKey, FormKey> mapping)
        {
        }
        
        #endregion
        
        #region Binary Translation
        public virtual void CopyInFromBinary(
            IScriptStructMember item,
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            PluginUtilityTranslation.SubrecordParse(
                record: item,
                frame: frame,
                translationParams: translationParams,
                fillStructs: ScriptStructMemberBinaryCreateTranslation.FillBinaryStructs);
        }
        
        #endregion
        
    }
    public partial class ScriptStructMemberCommon
    {
        public static readonly ScriptStructMemberCommon Instance = new ScriptStructMemberCommon();

        public ScriptStructMember.Mask<bool> GetEqualsMask(
            IScriptStructMemberGetter item,
            IScriptStructMemberGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new ScriptStructMember.Mask<bool>(false);
            ((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }
        
        public void FillEqualsMask(
            IScriptStructMemberGetter item,
            IScriptStructMemberGetter rhs,
            ScriptStructMember.Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.MemberName = string.Equals(item.MemberName, rhs.MemberName);
            ret.MemberFlags = item.MemberFlags == rhs.MemberFlags;
            ret.MemberProperties = item.MemberProperties.CollectionEqualsHelper(
                rhs.MemberProperties,
                (loqLhs, loqRhs) => loqLhs.GetEqualsMask(loqRhs, include),
                include);
        }
        
        public string ToString(
            IScriptStructMemberGetter item,
            string? name = null,
            ScriptStructMember.Mask<bool>? printMask = null)
        {
            var fg = new FileGeneration();
            ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
            return fg.ToString();
        }
        
        public void ToString(
            IScriptStructMemberGetter item,
            FileGeneration fg,
            string? name = null,
            ScriptStructMember.Mask<bool>? printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"ScriptStructMember =>");
            }
            else
            {
                fg.AppendLine($"{name} (ScriptStructMember) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                ToStringFields(
                    item: item,
                    fg: fg,
                    printMask: printMask);
            }
            fg.AppendLine("]");
        }
        
        protected static void ToStringFields(
            IScriptStructMemberGetter item,
            FileGeneration fg,
            ScriptStructMember.Mask<bool>? printMask = null)
        {
            if (printMask?.MemberName ?? true)
            {
                fg.AppendItem(item.MemberName, "MemberName");
            }
            if (printMask?.MemberFlags ?? true)
            {
                fg.AppendItem(item.MemberFlags, "MemberFlags");
            }
            if (printMask?.MemberProperties?.Overall ?? true)
            {
                fg.AppendLine("MemberProperties =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    foreach (var subItem in item.MemberProperties)
                    {
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            subItem?.ToString(fg, "Item");
                        }
                        fg.AppendLine("]");
                    }
                }
                fg.AppendLine("]");
            }
        }
        
        #region Equals and Hash
        public virtual bool Equals(
            IScriptStructMemberGetter? lhs,
            IScriptStructMemberGetter? rhs,
            TranslationCrystal? crystal)
        {
            if (!EqualsMaskHelper.RefEquality(lhs, rhs, out var isEqual)) return isEqual;
            if ((crystal?.GetShouldTranslate((int)ScriptStructMember_FieldIndex.MemberName) ?? true))
            {
                if (!string.Equals(lhs.MemberName, rhs.MemberName)) return false;
            }
            if ((crystal?.GetShouldTranslate((int)ScriptStructMember_FieldIndex.MemberFlags) ?? true))
            {
                if (lhs.MemberFlags != rhs.MemberFlags) return false;
            }
            if ((crystal?.GetShouldTranslate((int)ScriptStructMember_FieldIndex.MemberProperties) ?? true))
            {
                if (!lhs.MemberProperties.SequenceEqualNullable(rhs.MemberProperties)) return false;
            }
            return true;
        }
        
        public virtual int GetHashCode(IScriptStructMemberGetter item)
        {
            var hash = new HashCode();
            hash.Add(item.MemberName);
            hash.Add(item.MemberFlags);
            hash.Add(item.MemberProperties);
            return hash.ToHashCode();
        }
        
        #endregion
        
        
        public object GetNew()
        {
            return ScriptStructMember.GetNew();
        }
        
        #region Mutagen
        public IEnumerable<IFormLinkGetter> GetContainedFormLinks(IScriptStructMemberGetter obj)
        {
            yield break;
        }
        
        #endregion
        
    }
    public partial class ScriptStructMemberSetterTranslationCommon
    {
        public static readonly ScriptStructMemberSetterTranslationCommon Instance = new ScriptStructMemberSetterTranslationCommon();

        #region DeepCopyIn
        public void DeepCopyIn(
            IScriptStructMember item,
            IScriptStructMemberGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask,
            bool deepCopy)
        {
            if ((copyMask?.GetShouldTranslate((int)ScriptStructMember_FieldIndex.MemberName) ?? true))
            {
                item.MemberName = rhs.MemberName;
            }
            if ((copyMask?.GetShouldTranslate((int)ScriptStructMember_FieldIndex.MemberFlags) ?? true))
            {
                item.MemberFlags = rhs.MemberFlags;
            }
            if ((copyMask?.GetShouldTranslate((int)ScriptStructMember_FieldIndex.MemberProperties) ?? true))
            {
                errorMask?.PushIndex((int)ScriptStructMember_FieldIndex.MemberProperties);
                try
                {
                    item.MemberProperties.SetTo(
                        rhs.MemberProperties
                        .Select(r =>
                        {
                            return r.DeepCopy(
                                errorMask: errorMask,
                                default(TranslationCrystal));
                        }));
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }
        
        #endregion
        
        public ScriptStructMember DeepCopy(
            IScriptStructMemberGetter item,
            ScriptStructMember.TranslationMask? copyMask = null)
        {
            ScriptStructMember ret = (ScriptStructMember)((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).GetNew();
            ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: null,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            return ret;
        }
        
        public ScriptStructMember DeepCopy(
            IScriptStructMemberGetter item,
            out ScriptStructMember.ErrorMask errorMask,
            ScriptStructMember.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ScriptStructMember ret = (ScriptStructMember)((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).GetNew();
            ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                ret,
                item,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            errorMask = ScriptStructMember.ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }
        
        public ScriptStructMember DeepCopy(
            IScriptStructMemberGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            ScriptStructMember ret = (ScriptStructMember)((ScriptStructMemberCommon)((IScriptStructMemberGetter)item).CommonInstance()!).GetNew();
            ((ScriptStructMemberSetterTranslationCommon)((IScriptStructMemberGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: true);
            return ret;
        }
        
    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4
{
    public partial class ScriptStructMember
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => ScriptStructMember_Registration.Instance;
        public static ScriptStructMember_Registration StaticRegistration => ScriptStructMember_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => ScriptStructMemberCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterInstance()
        {
            return ScriptStructMemberSetterCommon.Instance;
        }
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => ScriptStructMemberSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IScriptStructMemberGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object IScriptStructMemberGetter.CommonSetterInstance() => this.CommonSetterInstance();
        [DebuggerStepThrough]
        object IScriptStructMemberGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

    }
}

#region Modules
#region Binary Translation
namespace Mutagen.Bethesda.Fallout4.Internals
{
    public partial class ScriptStructMemberBinaryWriteTranslation : IBinaryWriteTranslator
    {
        public readonly static ScriptStructMemberBinaryWriteTranslation Instance = new ScriptStructMemberBinaryWriteTranslation();

        public static void WriteEmbedded(
            IScriptStructMemberGetter item,
            MutagenWriter writer)
        {
        }

        public void Write(
            MutagenWriter writer,
            IScriptStructMemberGetter item,
            TypedWriteParams? translationParams = null)
        {
            WriteEmbedded(
                item: item,
                writer: writer);
        }

        public void Write(
            MutagenWriter writer,
            object item,
            TypedWriteParams? translationParams = null)
        {
            Write(
                item: (IScriptStructMemberGetter)item,
                writer: writer,
                translationParams: translationParams);
        }

    }

    public partial class ScriptStructMemberBinaryCreateTranslation
    {
        public readonly static ScriptStructMemberBinaryCreateTranslation Instance = new ScriptStructMemberBinaryCreateTranslation();

        public static void FillBinaryStructs(
            IScriptStructMember item,
            MutagenFrame frame)
        {
        }

    }

}
namespace Mutagen.Bethesda.Fallout4
{
    #region Binary Write Mixins
    public static class ScriptStructMemberBinaryTranslationMixIn
    {
        public static void WriteToBinary(
            this IScriptStructMemberGetter item,
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((ScriptStructMemberBinaryWriteTranslation)item.BinaryWriteTranslator).Write(
                item: item,
                writer: writer,
                translationParams: translationParams);
        }

    }
    #endregion


}
namespace Mutagen.Bethesda.Fallout4.Internals
{
    public partial class ScriptStructMemberBinaryOverlay :
        PluginBinaryOverlay,
        IScriptStructMemberGetter
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => ScriptStructMember_Registration.Instance;
        public static ScriptStructMember_Registration StaticRegistration => ScriptStructMember_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => ScriptStructMemberCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => ScriptStructMemberSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IScriptStructMemberGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object? IScriptStructMemberGetter.CommonSetterInstance() => null;
        [DebuggerStepThrough]
        object IScriptStructMemberGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => ScriptStructMemberBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((ScriptStructMemberBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }

        partial void CustomFactoryEnd(
            OverlayStream stream,
            int finalPos,
            int offset);

        partial void CustomCtor();
        protected ScriptStructMemberBinaryOverlay(
            ReadOnlyMemorySlice<byte> bytes,
            BinaryOverlayFactoryPackage package)
            : base(
                bytes: bytes,
                package: package)
        {
            this.CustomCtor();
        }

        public static ScriptStructMemberBinaryOverlay ScriptStructMemberFactory(
            OverlayStream stream,
            BinaryOverlayFactoryPackage package,
            TypedParseParams? parseParams = null)
        {
            var ret = new ScriptStructMemberBinaryOverlay(
                bytes: stream.RemainingMemory,
                package: package);
            int offset = stream.Position;
            ret.CustomFactoryEnd(
                stream: stream,
                finalPos: stream.Length,
                offset: offset);
            return ret;
        }

        public static ScriptStructMemberBinaryOverlay ScriptStructMemberFactory(
            ReadOnlyMemorySlice<byte> slice,
            BinaryOverlayFactoryPackage package,
            TypedParseParams? parseParams = null)
        {
            return ScriptStructMemberFactory(
                stream: new OverlayStream(slice, package),
                package: package,
                parseParams: parseParams);
        }

        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            ScriptStructMemberMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IScriptStructMemberGetter rhs) return false;
            return ((ScriptStructMemberCommon)((IScriptStructMemberGetter)this).CommonInstance()!).Equals(this, rhs, crystal: null);
        }

        public bool Equals(IScriptStructMemberGetter? obj)
        {
            return ((ScriptStructMemberCommon)((IScriptStructMemberGetter)this).CommonInstance()!).Equals(this, obj, crystal: null);
        }

        public override int GetHashCode() => ((ScriptStructMemberCommon)((IScriptStructMemberGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

    }

}
#endregion

#endregion

