/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
#region Usings
using Loqui;
using Loqui.Internal;
using Mutagen.Bethesda.Binary;
using Mutagen.Bethesda.Fallout4.Internals;
using Mutagen.Bethesda.Internals;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Binary.Overlay;
using Mutagen.Bethesda.Plugins.Binary.Streams;
using Mutagen.Bethesda.Plugins.Binary.Translations;
using Mutagen.Bethesda.Plugins.Exceptions;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Plugins.Records.Internals;
using Mutagen.Bethesda.Translations.Binary;
using Noggog;
using System;
using System.Buffers.Binary;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Text;
#endregion

#nullable enable
namespace Mutagen.Bethesda.Fallout4
{
    #region Class
    public partial class ScriptPropertyStructMember :
        IEquatable<IScriptPropertyStructMemberGetter>,
        ILoquiObjectSetter<ScriptPropertyStructMember>,
        IScriptPropertyStructMember
    {
        #region Ctor
        public ScriptPropertyStructMember()
        {
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region ScriptPropertyStructMemberName
        public String ScriptPropertyStructMemberName { get; set; } = string.Empty;
        #endregion
        #region ScriptPropertyStructMemberFlags
        public readonly static ScriptProperty.Flag _ScriptPropertyStructMemberFlags_Default = ScriptProperty.Flag.Edited;
        public ScriptProperty.Flag ScriptPropertyStructMemberFlags { get; set; } = _ScriptPropertyStructMemberFlags_Default;
        #endregion

        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            ScriptPropertyStructMemberMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IScriptPropertyStructMemberGetter rhs) return false;
            return ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)this).CommonInstance()!).Equals(this, rhs, crystal: null);
        }

        public bool Equals(IScriptPropertyStructMemberGetter? obj)
        {
            return ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)this).CommonInstance()!).Equals(this, obj, crystal: null);
        }

        public override int GetHashCode() => ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

        #region Mask
        public class Mask<TItem> :
            IEquatable<Mask<TItem>>,
            IMask<TItem>
        {
            #region Ctors
            public Mask(TItem initialValue)
            {
                this.ScriptPropertyStructMemberName = initialValue;
                this.ScriptPropertyStructMemberFlags = initialValue;
            }

            public Mask(
                TItem ScriptPropertyStructMemberName,
                TItem ScriptPropertyStructMemberFlags)
            {
                this.ScriptPropertyStructMemberName = ScriptPropertyStructMemberName;
                this.ScriptPropertyStructMemberFlags = ScriptPropertyStructMemberFlags;
            }

            #pragma warning disable CS8618
            protected Mask()
            {
            }
            #pragma warning restore CS8618

            #endregion

            #region Members
            public TItem ScriptPropertyStructMemberName;
            public TItem ScriptPropertyStructMemberFlags;
            #endregion

            #region Equals
            public override bool Equals(object? obj)
            {
                if (!(obj is Mask<TItem> rhs)) return false;
                return Equals(rhs);
            }

            public bool Equals(Mask<TItem>? rhs)
            {
                if (rhs == null) return false;
                if (!object.Equals(this.ScriptPropertyStructMemberName, rhs.ScriptPropertyStructMemberName)) return false;
                if (!object.Equals(this.ScriptPropertyStructMemberFlags, rhs.ScriptPropertyStructMemberFlags)) return false;
                return true;
            }
            public override int GetHashCode()
            {
                var hash = new HashCode();
                hash.Add(this.ScriptPropertyStructMemberName);
                hash.Add(this.ScriptPropertyStructMemberFlags);
                return hash.ToHashCode();
            }

            #endregion

            #region All
            public bool All(Func<TItem, bool> eval)
            {
                if (!eval(this.ScriptPropertyStructMemberName)) return false;
                if (!eval(this.ScriptPropertyStructMemberFlags)) return false;
                return true;
            }
            #endregion

            #region Any
            public bool Any(Func<TItem, bool> eval)
            {
                if (eval(this.ScriptPropertyStructMemberName)) return true;
                if (eval(this.ScriptPropertyStructMemberFlags)) return true;
                return false;
            }
            #endregion

            #region Translate
            public Mask<R> Translate<R>(Func<TItem, R> eval)
            {
                var ret = new ScriptPropertyStructMember.Mask<R>();
                this.Translate_InternalFill(ret, eval);
                return ret;
            }

            protected void Translate_InternalFill<R>(Mask<R> obj, Func<TItem, R> eval)
            {
                obj.ScriptPropertyStructMemberName = eval(this.ScriptPropertyStructMemberName);
                obj.ScriptPropertyStructMemberFlags = eval(this.ScriptPropertyStructMemberFlags);
            }
            #endregion

            #region To String
            public override string ToString()
            {
                return ToString(printMask: null);
            }

            public string ToString(ScriptPropertyStructMember.Mask<bool>? printMask = null)
            {
                var fg = new FileGeneration();
                ToString(fg, printMask);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, ScriptPropertyStructMember.Mask<bool>? printMask = null)
            {
                fg.AppendLine($"{nameof(ScriptPropertyStructMember.Mask<TItem>)} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (printMask?.ScriptPropertyStructMemberName ?? true)
                    {
                        fg.AppendItem(ScriptPropertyStructMemberName, "ScriptPropertyStructMemberName");
                    }
                    if (printMask?.ScriptPropertyStructMemberFlags ?? true)
                    {
                        fg.AppendItem(ScriptPropertyStructMemberFlags, "ScriptPropertyStructMemberFlags");
                    }
                }
                fg.AppendLine("]");
            }
            #endregion

        }

        public class ErrorMask :
            IErrorMask,
            IErrorMask<ErrorMask>
        {
            #region Members
            public Exception? Overall { get; set; }
            private List<string>? _warnings;
            public List<string> Warnings
            {
                get
                {
                    if (_warnings == null)
                    {
                        _warnings = new List<string>();
                    }
                    return _warnings;
                }
            }
            public Exception? ScriptPropertyStructMemberName;
            public Exception? ScriptPropertyStructMemberFlags;
            #endregion

            #region IErrorMask
            public object? GetNthMask(int index)
            {
                ScriptPropertyStructMember_FieldIndex enu = (ScriptPropertyStructMember_FieldIndex)index;
                switch (enu)
                {
                    case ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberName:
                        return ScriptPropertyStructMemberName;
                    case ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberFlags:
                        return ScriptPropertyStructMemberFlags;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthException(int index, Exception ex)
            {
                ScriptPropertyStructMember_FieldIndex enu = (ScriptPropertyStructMember_FieldIndex)index;
                switch (enu)
                {
                    case ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberName:
                        this.ScriptPropertyStructMemberName = ex;
                        break;
                    case ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberFlags:
                        this.ScriptPropertyStructMemberFlags = ex;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public void SetNthMask(int index, object obj)
            {
                ScriptPropertyStructMember_FieldIndex enu = (ScriptPropertyStructMember_FieldIndex)index;
                switch (enu)
                {
                    case ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberName:
                        this.ScriptPropertyStructMemberName = (Exception?)obj;
                        break;
                    case ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberFlags:
                        this.ScriptPropertyStructMemberFlags = (Exception?)obj;
                        break;
                    default:
                        throw new ArgumentException($"Index is out of range: {index}");
                }
            }

            public bool IsInError()
            {
                if (Overall != null) return true;
                if (ScriptPropertyStructMemberName != null) return true;
                if (ScriptPropertyStructMemberFlags != null) return true;
                return false;
            }
            #endregion

            #region To String
            public override string ToString()
            {
                var fg = new FileGeneration();
                ToString(fg, null);
                return fg.ToString();
            }

            public void ToString(FileGeneration fg, string? name = null)
            {
                fg.AppendLine($"{(name ?? "ErrorMask")} =>");
                fg.AppendLine("[");
                using (new DepthWrapper(fg))
                {
                    if (this.Overall != null)
                    {
                        fg.AppendLine("Overall =>");
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            fg.AppendLine($"{this.Overall}");
                        }
                        fg.AppendLine("]");
                    }
                    ToString_FillInternal(fg);
                }
                fg.AppendLine("]");
            }
            protected void ToString_FillInternal(FileGeneration fg)
            {
                fg.AppendItem(ScriptPropertyStructMemberName, "ScriptPropertyStructMemberName");
                fg.AppendItem(ScriptPropertyStructMemberFlags, "ScriptPropertyStructMemberFlags");
            }
            #endregion

            #region Combine
            public ErrorMask Combine(ErrorMask? rhs)
            {
                if (rhs == null) return this;
                var ret = new ErrorMask();
                ret.ScriptPropertyStructMemberName = this.ScriptPropertyStructMemberName.Combine(rhs.ScriptPropertyStructMemberName);
                ret.ScriptPropertyStructMemberFlags = this.ScriptPropertyStructMemberFlags.Combine(rhs.ScriptPropertyStructMemberFlags);
                return ret;
            }
            public static ErrorMask? Combine(ErrorMask? lhs, ErrorMask? rhs)
            {
                if (lhs != null && rhs != null) return lhs.Combine(rhs);
                return lhs ?? rhs;
            }
            #endregion

            #region Factory
            public static ErrorMask Factory(ErrorMaskBuilder errorMask)
            {
                return new ErrorMask();
            }
            #endregion

        }
        public class TranslationMask : ITranslationMask
        {
            #region Members
            private TranslationCrystal? _crystal;
            public readonly bool DefaultOn;
            public bool OnOverall;
            public bool ScriptPropertyStructMemberName;
            public bool ScriptPropertyStructMemberFlags;
            #endregion

            #region Ctors
            public TranslationMask(
                bool defaultOn,
                bool onOverall = true)
            {
                this.DefaultOn = defaultOn;
                this.OnOverall = onOverall;
                this.ScriptPropertyStructMemberName = defaultOn;
                this.ScriptPropertyStructMemberFlags = defaultOn;
            }

            #endregion

            public TranslationCrystal GetCrystal()
            {
                if (_crystal != null) return _crystal;
                var ret = new List<(bool On, TranslationCrystal? SubCrystal)>();
                GetCrystal(ret);
                _crystal = new TranslationCrystal(ret.ToArray());
                return _crystal;
            }

            protected void GetCrystal(List<(bool On, TranslationCrystal? SubCrystal)> ret)
            {
                ret.Add((ScriptPropertyStructMemberName, null));
                ret.Add((ScriptPropertyStructMemberFlags, null));
            }

            public static implicit operator TranslationMask(bool defaultOn)
            {
                return new TranslationMask(defaultOn: defaultOn, onOverall: defaultOn);
            }

        }
        #endregion

        #region Binary Translation
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => ScriptPropertyStructMemberBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((ScriptPropertyStructMemberBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }
        #region Binary Create
        public static ScriptPropertyStructMember CreateFromBinary(
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            var ret = new ScriptPropertyStructMember();
            ((ScriptPropertyStructMemberSetterCommon)((IScriptPropertyStructMemberGetter)ret).CommonSetterInstance()!).CopyInFromBinary(
                item: ret,
                frame: frame,
                translationParams: translationParams);
            return ret;
        }

        #endregion

        public static bool TryCreateFromBinary(
            MutagenFrame frame,
            out ScriptPropertyStructMember item,
            TypedParseParams? translationParams = null)
        {
            var startPos = frame.Position;
            item = CreateFromBinary(
                frame: frame,
                translationParams: translationParams);
            return startPos != frame.Position;
        }
        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);

        void IClearable.Clear()
        {
            ((ScriptPropertyStructMemberSetterCommon)((IScriptPropertyStructMemberGetter)this).CommonSetterInstance()!).Clear(this);
        }

        internal static ScriptPropertyStructMember GetNew()
        {
            return new ScriptPropertyStructMember();
        }

    }
    #endregion

    #region Interface
    public partial interface IScriptPropertyStructMember :
        ILoquiObjectSetter<IScriptPropertyStructMember>,
        IScriptPropertyStructMemberGetter
    {
        new String ScriptPropertyStructMemberName { get; set; }
        new ScriptProperty.Flag ScriptPropertyStructMemberFlags { get; set; }
    }

    public partial interface IScriptPropertyStructMemberGetter :
        ILoquiObject,
        IBinaryItem,
        ILoquiObject<IScriptPropertyStructMemberGetter>
    {
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object? CommonSetterInstance();
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        object CommonSetterTranslationInstance();
        static ILoquiRegistration StaticRegistration => ScriptPropertyStructMember_Registration.Instance;
        String ScriptPropertyStructMemberName { get; }
        ScriptProperty.Flag ScriptPropertyStructMemberFlags { get; }

    }

    #endregion

    #region Common MixIn
    public static partial class ScriptPropertyStructMemberMixIn
    {
        public static void Clear(this IScriptPropertyStructMember item)
        {
            ((ScriptPropertyStructMemberSetterCommon)((IScriptPropertyStructMemberGetter)item).CommonSetterInstance()!).Clear(item: item);
        }

        public static ScriptPropertyStructMember.Mask<bool> GetEqualsMask(
            this IScriptPropertyStructMemberGetter item,
            IScriptPropertyStructMemberGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            return ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).GetEqualsMask(
                item: item,
                rhs: rhs,
                include: include);
        }

        public static string ToString(
            this IScriptPropertyStructMemberGetter item,
            string? name = null,
            ScriptPropertyStructMember.Mask<bool>? printMask = null)
        {
            return ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).ToString(
                item: item,
                name: name,
                printMask: printMask);
        }

        public static void ToString(
            this IScriptPropertyStructMemberGetter item,
            FileGeneration fg,
            string? name = null,
            ScriptPropertyStructMember.Mask<bool>? printMask = null)
        {
            ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
        }

        public static bool Equals(
            this IScriptPropertyStructMemberGetter item,
            IScriptPropertyStructMemberGetter rhs,
            ScriptPropertyStructMember.TranslationMask? equalsMask = null)
        {
            return ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).Equals(
                lhs: item,
                rhs: rhs,
                crystal: equalsMask?.GetCrystal());
        }

        public static void DeepCopyIn(
            this IScriptPropertyStructMember lhs,
            IScriptPropertyStructMemberGetter rhs)
        {
            ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: default,
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IScriptPropertyStructMember lhs,
            IScriptPropertyStructMemberGetter rhs,
            ScriptPropertyStructMember.TranslationMask? copyMask = null)
        {
            ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: default,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
        }

        public static void DeepCopyIn(
            this IScriptPropertyStructMember lhs,
            IScriptPropertyStructMemberGetter rhs,
            out ScriptPropertyStructMember.ErrorMask errorMask,
            ScriptPropertyStructMember.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: false);
            errorMask = ScriptPropertyStructMember.ErrorMask.Factory(errorMaskBuilder);
        }

        public static void DeepCopyIn(
            this IScriptPropertyStructMember lhs,
            IScriptPropertyStructMemberGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask)
        {
            ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)lhs).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: lhs,
                rhs: rhs,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: false);
        }

        public static ScriptPropertyStructMember DeepCopy(
            this IScriptPropertyStructMemberGetter item,
            ScriptPropertyStructMember.TranslationMask? copyMask = null)
        {
            return ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask);
        }

        public static ScriptPropertyStructMember DeepCopy(
            this IScriptPropertyStructMemberGetter item,
            out ScriptPropertyStructMember.ErrorMask errorMask,
            ScriptPropertyStructMember.TranslationMask? copyMask = null)
        {
            return ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: out errorMask);
        }

        public static ScriptPropertyStructMember DeepCopy(
            this IScriptPropertyStructMemberGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            return ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)item).CommonSetterTranslationInstance()!).DeepCopy(
                item: item,
                copyMask: copyMask,
                errorMask: errorMask);
        }

        #region Binary Translation
        public static void CopyInFromBinary(
            this IScriptPropertyStructMember item,
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            ((ScriptPropertyStructMemberSetterCommon)((IScriptPropertyStructMemberGetter)item).CommonSetterInstance()!).CopyInFromBinary(
                item: item,
                frame: frame,
                translationParams: translationParams);
        }

        #endregion

    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4.Internals
{
    #region Field Index
    public enum ScriptPropertyStructMember_FieldIndex
    {
        ScriptPropertyStructMemberName = 0,
        ScriptPropertyStructMemberFlags = 1,
    }
    #endregion

    #region Registration
    public partial class ScriptPropertyStructMember_Registration : ILoquiRegistration
    {
        public static readonly ScriptPropertyStructMember_Registration Instance = new ScriptPropertyStructMember_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_Fallout4.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_Fallout4.ProtocolKey,
            msgID: 215,
            version: 0);

        public const string GUID = "9893a585-c66c-4bd5-882c-ba2eceeeca33";

        public const ushort AdditionalFieldCount = 2;

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(ScriptPropertyStructMember.Mask<>);

        public static readonly Type ErrorMaskType = typeof(ScriptPropertyStructMember.ErrorMask);

        public static readonly Type ClassType = typeof(ScriptPropertyStructMember);

        public static readonly Type GetterType = typeof(IScriptPropertyStructMemberGetter);

        public static readonly Type? InternalGetterType = null;

        public static readonly Type SetterType = typeof(IScriptPropertyStructMember);

        public static readonly Type? InternalSetterType = null;

        public const string FullName = "Mutagen.Bethesda.Fallout4.ScriptPropertyStructMember";

        public const string Name = "ScriptPropertyStructMember";

        public const string Namespace = "Mutagen.Bethesda.Fallout4";

        public const byte GenericCount = 0;

        public static readonly Type? GenericRegistrationType = null;

        public static readonly Type BinaryWriteTranslation = typeof(ScriptPropertyStructMemberBinaryWriteTranslation);
        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type? ILoquiRegistration.InternalSetterType => InternalSetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type? ILoquiRegistration.InternalGetterType => InternalGetterType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type? ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => throw new NotImplementedException();
        string ILoquiRegistration.GetNthName(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsNthDerivative(ushort index) => throw new NotImplementedException();
        bool ILoquiRegistration.IsProtected(ushort index) => throw new NotImplementedException();
        Type ILoquiRegistration.GetNthType(ushort index) => throw new NotImplementedException();
        #endregion

    }
    #endregion

    #region Common
    public partial class ScriptPropertyStructMemberSetterCommon
    {
        public static readonly ScriptPropertyStructMemberSetterCommon Instance = new ScriptPropertyStructMemberSetterCommon();

        partial void ClearPartial();
        
        public void Clear(IScriptPropertyStructMember item)
        {
            ClearPartial();
            item.ScriptPropertyStructMemberName = string.Empty;
            item.ScriptPropertyStructMemberFlags = ScriptPropertyStructMember._ScriptPropertyStructMemberFlags_Default;
        }
        
        #region Mutagen
        public void RemapLinks(IScriptPropertyStructMember obj, IReadOnlyDictionary<FormKey, FormKey> mapping)
        {
        }
        
        #endregion
        
        #region Binary Translation
        public virtual void CopyInFromBinary(
            IScriptPropertyStructMember item,
            MutagenFrame frame,
            TypedParseParams? translationParams = null)
        {
            PluginUtilityTranslation.SubrecordParse(
                record: item,
                frame: frame,
                translationParams: translationParams,
                fillStructs: ScriptPropertyStructMemberBinaryCreateTranslation.FillBinaryStructs);
        }
        
        #endregion
        
    }
    public partial class ScriptPropertyStructMemberCommon
    {
        public static readonly ScriptPropertyStructMemberCommon Instance = new ScriptPropertyStructMemberCommon();

        public ScriptPropertyStructMember.Mask<bool> GetEqualsMask(
            IScriptPropertyStructMemberGetter item,
            IScriptPropertyStructMemberGetter rhs,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            var ret = new ScriptPropertyStructMember.Mask<bool>(false);
            ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).FillEqualsMask(
                item: item,
                rhs: rhs,
                ret: ret,
                include: include);
            return ret;
        }
        
        public void FillEqualsMask(
            IScriptPropertyStructMemberGetter item,
            IScriptPropertyStructMemberGetter rhs,
            ScriptPropertyStructMember.Mask<bool> ret,
            EqualsMaskHelper.Include include = EqualsMaskHelper.Include.All)
        {
            if (rhs == null) return;
            ret.ScriptPropertyStructMemberName = string.Equals(item.ScriptPropertyStructMemberName, rhs.ScriptPropertyStructMemberName);
            ret.ScriptPropertyStructMemberFlags = item.ScriptPropertyStructMemberFlags == rhs.ScriptPropertyStructMemberFlags;
        }
        
        public string ToString(
            IScriptPropertyStructMemberGetter item,
            string? name = null,
            ScriptPropertyStructMember.Mask<bool>? printMask = null)
        {
            var fg = new FileGeneration();
            ToString(
                item: item,
                fg: fg,
                name: name,
                printMask: printMask);
            return fg.ToString();
        }
        
        public void ToString(
            IScriptPropertyStructMemberGetter item,
            FileGeneration fg,
            string? name = null,
            ScriptPropertyStructMember.Mask<bool>? printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"ScriptPropertyStructMember =>");
            }
            else
            {
                fg.AppendLine($"{name} (ScriptPropertyStructMember) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                ToStringFields(
                    item: item,
                    fg: fg,
                    printMask: printMask);
            }
            fg.AppendLine("]");
        }
        
        protected static void ToStringFields(
            IScriptPropertyStructMemberGetter item,
            FileGeneration fg,
            ScriptPropertyStructMember.Mask<bool>? printMask = null)
        {
            if (printMask?.ScriptPropertyStructMemberName ?? true)
            {
                fg.AppendItem(item.ScriptPropertyStructMemberName, "ScriptPropertyStructMemberName");
            }
            if (printMask?.ScriptPropertyStructMemberFlags ?? true)
            {
                fg.AppendItem(item.ScriptPropertyStructMemberFlags, "ScriptPropertyStructMemberFlags");
            }
        }
        
        #region Equals and Hash
        public virtual bool Equals(
            IScriptPropertyStructMemberGetter? lhs,
            IScriptPropertyStructMemberGetter? rhs,
            TranslationCrystal? crystal)
        {
            if (!EqualsMaskHelper.RefEquality(lhs, rhs, out var isEqual)) return isEqual;
            if ((crystal?.GetShouldTranslate((int)ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberName) ?? true))
            {
                if (!string.Equals(lhs.ScriptPropertyStructMemberName, rhs.ScriptPropertyStructMemberName)) return false;
            }
            if ((crystal?.GetShouldTranslate((int)ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberFlags) ?? true))
            {
                if (lhs.ScriptPropertyStructMemberFlags != rhs.ScriptPropertyStructMemberFlags) return false;
            }
            return true;
        }
        
        public virtual int GetHashCode(IScriptPropertyStructMemberGetter item)
        {
            var hash = new HashCode();
            hash.Add(item.ScriptPropertyStructMemberName);
            hash.Add(item.ScriptPropertyStructMemberFlags);
            return hash.ToHashCode();
        }
        
        #endregion
        
        
        public object GetNew()
        {
            return ScriptPropertyStructMember.GetNew();
        }
        
        #region Mutagen
        public IEnumerable<IFormLinkGetter> GetContainedFormLinks(IScriptPropertyStructMemberGetter obj)
        {
            yield break;
        }
        
        #endregion
        
    }
    public partial class ScriptPropertyStructMemberSetterTranslationCommon
    {
        public static readonly ScriptPropertyStructMemberSetterTranslationCommon Instance = new ScriptPropertyStructMemberSetterTranslationCommon();

        #region DeepCopyIn
        public void DeepCopyIn(
            IScriptPropertyStructMember item,
            IScriptPropertyStructMemberGetter rhs,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask,
            bool deepCopy)
        {
            if ((copyMask?.GetShouldTranslate((int)ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberName) ?? true))
            {
                item.ScriptPropertyStructMemberName = rhs.ScriptPropertyStructMemberName;
            }
            if ((copyMask?.GetShouldTranslate((int)ScriptPropertyStructMember_FieldIndex.ScriptPropertyStructMemberFlags) ?? true))
            {
                item.ScriptPropertyStructMemberFlags = rhs.ScriptPropertyStructMemberFlags;
            }
        }
        
        #endregion
        
        public ScriptPropertyStructMember DeepCopy(
            IScriptPropertyStructMemberGetter item,
            ScriptPropertyStructMember.TranslationMask? copyMask = null)
        {
            ScriptPropertyStructMember ret = (ScriptPropertyStructMember)((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).GetNew();
            ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: null,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            return ret;
        }
        
        public ScriptPropertyStructMember DeepCopy(
            IScriptPropertyStructMemberGetter item,
            out ScriptPropertyStructMember.ErrorMask errorMask,
            ScriptPropertyStructMember.TranslationMask? copyMask = null)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ScriptPropertyStructMember ret = (ScriptPropertyStructMember)((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).GetNew();
            ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                ret,
                item,
                errorMask: errorMaskBuilder,
                copyMask: copyMask?.GetCrystal(),
                deepCopy: true);
            errorMask = ScriptPropertyStructMember.ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }
        
        public ScriptPropertyStructMember DeepCopy(
            IScriptPropertyStructMemberGetter item,
            ErrorMaskBuilder? errorMask,
            TranslationCrystal? copyMask = null)
        {
            ScriptPropertyStructMember ret = (ScriptPropertyStructMember)((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)item).CommonInstance()!).GetNew();
            ((ScriptPropertyStructMemberSetterTranslationCommon)((IScriptPropertyStructMemberGetter)ret).CommonSetterTranslationInstance()!).DeepCopyIn(
                item: ret,
                rhs: item,
                errorMask: errorMask,
                copyMask: copyMask,
                deepCopy: true);
            return ret;
        }
        
    }
    #endregion

}

namespace Mutagen.Bethesda.Fallout4
{
    public partial class ScriptPropertyStructMember
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => ScriptPropertyStructMember_Registration.Instance;
        public static ScriptPropertyStructMember_Registration StaticRegistration => ScriptPropertyStructMember_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => ScriptPropertyStructMemberCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterInstance()
        {
            return ScriptPropertyStructMemberSetterCommon.Instance;
        }
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => ScriptPropertyStructMemberSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IScriptPropertyStructMemberGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object IScriptPropertyStructMemberGetter.CommonSetterInstance() => this.CommonSetterInstance();
        [DebuggerStepThrough]
        object IScriptPropertyStructMemberGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

    }
}

#region Modules
#region Binary Translation
namespace Mutagen.Bethesda.Fallout4.Internals
{
    public partial class ScriptPropertyStructMemberBinaryWriteTranslation : IBinaryWriteTranslator
    {
        public readonly static ScriptPropertyStructMemberBinaryWriteTranslation Instance = new ScriptPropertyStructMemberBinaryWriteTranslation();

        public static void WriteEmbedded(
            IScriptPropertyStructMemberGetter item,
            MutagenWriter writer)
        {
        }

        public void Write(
            MutagenWriter writer,
            IScriptPropertyStructMemberGetter item,
            TypedWriteParams? translationParams = null)
        {
            WriteEmbedded(
                item: item,
                writer: writer);
        }

        public void Write(
            MutagenWriter writer,
            object item,
            TypedWriteParams? translationParams = null)
        {
            Write(
                item: (IScriptPropertyStructMemberGetter)item,
                writer: writer,
                translationParams: translationParams);
        }

    }

    public partial class ScriptPropertyStructMemberBinaryCreateTranslation
    {
        public readonly static ScriptPropertyStructMemberBinaryCreateTranslation Instance = new ScriptPropertyStructMemberBinaryCreateTranslation();

        public static void FillBinaryStructs(
            IScriptPropertyStructMember item,
            MutagenFrame frame)
        {
        }

    }

}
namespace Mutagen.Bethesda.Fallout4
{
    #region Binary Write Mixins
    public static class ScriptPropertyStructMemberBinaryTranslationMixIn
    {
        public static void WriteToBinary(
            this IScriptPropertyStructMemberGetter item,
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((ScriptPropertyStructMemberBinaryWriteTranslation)item.BinaryWriteTranslator).Write(
                item: item,
                writer: writer,
                translationParams: translationParams);
        }

    }
    #endregion


}
namespace Mutagen.Bethesda.Fallout4.Internals
{
    public partial class ScriptPropertyStructMemberBinaryOverlay :
        PluginBinaryOverlay,
        IScriptPropertyStructMemberGetter
    {
        #region Common Routing
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => ScriptPropertyStructMember_Registration.Instance;
        public static ScriptPropertyStructMember_Registration StaticRegistration => ScriptPropertyStructMember_Registration.Instance;
        [DebuggerStepThrough]
        protected object CommonInstance() => ScriptPropertyStructMemberCommon.Instance;
        [DebuggerStepThrough]
        protected object CommonSetterTranslationInstance() => ScriptPropertyStructMemberSetterTranslationCommon.Instance;
        [DebuggerStepThrough]
        object IScriptPropertyStructMemberGetter.CommonInstance() => this.CommonInstance();
        [DebuggerStepThrough]
        object? IScriptPropertyStructMemberGetter.CommonSetterInstance() => null;
        [DebuggerStepThrough]
        object IScriptPropertyStructMemberGetter.CommonSetterTranslationInstance() => this.CommonSetterTranslationInstance();

        #endregion

        void IPrintable.ToString(FileGeneration fg, string? name) => this.ToString(fg, name);

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        protected object BinaryWriteTranslator => ScriptPropertyStructMemberBinaryWriteTranslation.Instance;
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        object IBinaryItem.BinaryWriteTranslator => this.BinaryWriteTranslator;
        void IBinaryItem.WriteToBinary(
            MutagenWriter writer,
            TypedWriteParams? translationParams = null)
        {
            ((ScriptPropertyStructMemberBinaryWriteTranslation)this.BinaryWriteTranslator).Write(
                item: this,
                writer: writer,
                translationParams: translationParams);
        }

        partial void CustomFactoryEnd(
            OverlayStream stream,
            int finalPos,
            int offset);

        partial void CustomCtor();
        protected ScriptPropertyStructMemberBinaryOverlay(
            ReadOnlyMemorySlice<byte> bytes,
            BinaryOverlayFactoryPackage package)
            : base(
                bytes: bytes,
                package: package)
        {
            this.CustomCtor();
        }

        public static ScriptPropertyStructMemberBinaryOverlay ScriptPropertyStructMemberFactory(
            OverlayStream stream,
            BinaryOverlayFactoryPackage package,
            TypedParseParams? parseParams = null)
        {
            var ret = new ScriptPropertyStructMemberBinaryOverlay(
                bytes: stream.RemainingMemory,
                package: package);
            int offset = stream.Position;
            ret.CustomFactoryEnd(
                stream: stream,
                finalPos: stream.Length,
                offset: offset);
            return ret;
        }

        public static ScriptPropertyStructMemberBinaryOverlay ScriptPropertyStructMemberFactory(
            ReadOnlyMemorySlice<byte> slice,
            BinaryOverlayFactoryPackage package,
            TypedParseParams? parseParams = null)
        {
            return ScriptPropertyStructMemberFactory(
                stream: new OverlayStream(slice, package),
                package: package,
                parseParams: parseParams);
        }

        #region To String

        public void ToString(
            FileGeneration fg,
            string? name = null)
        {
            ScriptPropertyStructMemberMixIn.ToString(
                item: this,
                name: name);
        }

        #endregion

        #region Equals and Hash
        public override bool Equals(object? obj)
        {
            if (obj is not IScriptPropertyStructMemberGetter rhs) return false;
            return ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)this).CommonInstance()!).Equals(this, rhs, crystal: null);
        }

        public bool Equals(IScriptPropertyStructMemberGetter? obj)
        {
            return ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)this).CommonInstance()!).Equals(this, obj, crystal: null);
        }

        public override int GetHashCode() => ((ScriptPropertyStructMemberCommon)((IScriptPropertyStructMemberGetter)this).CommonInstance()!).GetHashCode(this);

        #endregion

    }

}
#endregion

#endregion

